let words = {
  types: [
    'cloud based',
    'voice controlled',
    'offline',
    'online',
    'solid state',
    'prototype',
    'pink',
    'TED talk about a',
    'mixed reality',
    'tasty',
    'gamified',
    'native',
    'web 2.0',
    'nearly invisble',
    'cheeky',
    'hololens',
    'security focused',
    'big pharma',
    'sourdough',
    'triple filtered',
    'coffee flavoured',
    '48k',
    'temperature controlled',
    'sweet',
    'real-life',
    'waterproof',
    'fruit themed',
    'premium',
    'dumbed down',
    'scalable',
    'social',
    'mobile',
    'disruptive',
    'hydrophobic',
    '360 degree',
    'weaponized',
    'shatterproof',
    'all singing, all dancing',
    'low energy',
    'rechargable',
    'crowdfunded',
    'vegan',
    'jumbo',
    'in car',
    'hands free',
    'static',
    'fully aware',
    'experimental',
    'automated',
    'crypto currency',
    'retro',
    'deep learning',
    'self-driving',
    'compressed',
    'condensed',
    'USB C',
    'digital',
    'analog',
    'really really tall',
    'supercooled',
    'single use',
    'biodegradable',
    'good value',
    'expensive',
    'limited edition',
    'intentionally abusive',
    'foreign',
    'self-censoring',
    'sleevless',
    'family-guy branded',
    'white-label',
    'unbranded',
    'shrek endorsed',
    'Friends themed',
    'spooky',
    'talking',
    'vampire based',
    'tasteless',
    'glittery',
    'organic',
    'consumer facing',
    'artisan',
    'backwards-compatible',
    'totally rad',
    'opinionated',
    'wearable',
    'totally silent',
    'deskdrop about a',
    'mobile first',
    'non-threatening',
    'gender specific'
  ],
  nouns: [
    'webcam',
    'instagram',
    'social currency',
    'drone delivery service',
    'videogame',
    '3d printer',
    'iOS app',
    'funk machine',
    'virtual pet',
    'jira board',
    'subreddit',
    'L E D panel',
    'fishing net',
    'email campaign',
    'episode of House',
    'motorboat',
    'innovation team simulator',
    'pizza oven',
    'apple TV app',
    'e-cig vapour',
    'raspberry pi clone',
    'slackbot',
    'photoshop plugin',
    'internet website',
    '4 O 4 page',
    'pop up shop',
    'experience',
    'vr experience',
    'think piece',
    'white paper',
    'webinar',
    'thing for dads',
    'pattern library',
    'Spotify playlist',
    'food alternative',
    'projector',
    'full body scanner',
    'airport security system',
    'oilrig visualizer',
    'winamp plugin',
    'control pad',
    'bookcase',
    'self driving car',
    'cash card',
    'firewall',
    'parody twitter account',
    'website kind of like tinder',
    'app similar to tripadvisor',
    'debugging mechanism',
    'liquid',
    'cameraphone',
    'camera',
    'record player',
    'audio format',
    'teapot',
    'set top box',
    'e-card',
    'craft beer dispenser',
    'nostalgia trip',
    'laptop cooler',
    'fake news'
  ],
  variations: [
    'written in elm',
    'but with beacons',
    'on a USB stick',
    'built for quantum computers',
    'to run on smart fridges',
    'but for girls',
    'without all the scandal',
    'integrated in to a suit of armour',
    'written in swift',
    'written in react native',
    'for Windows 10',
    'for banks',
    'that lives in your garden',
    'designed by a famous racing car driver',
    'as a service',
    'with touch I D',
    'running on Tizen',
    'but for dogs and horses and things like that',
    'that never gets wet',
    '. jon shave edition',
    'that frightens away bees',
    'but more premium',
    'for businesses',
    'that your mum could use',
    'simulator',
    'written by my mates sister',
    'art book',
    'that attracts all types of bees',
    'that calls the police',
    'for grieving widows',
    'that cleans and straightens your teeth',
    'run from a raspberry pi inside a top hat',
    '- and you can even eat the packaging',
    'that remembers where you left off',
    'that fits neatly on the outside of your pants',
    'that gets bigger in water',
    'that fits neatly between two vertebrae',
    'narrated by the cast of Seinfeld',
    'that always know where you are',
    'that tracks your purchases',
    'like Nick Cage had in that film',
    'with an interface like the one in minority report',
    'rendering the whole thing pointless',
    '- but you mustn\'t touch it',
    'for hospitals and hotels',
    'that knows where you are going to sit',
    'that breaks down harmlessly in stomach acids',
    'compatible with Lego',
    'for meeting new people',
    '- like bitcoin',
    'for taking selfies',
    'for taking selfies of other people',
    'but without a headphone socket',
    'that doesn’t hurt when you take it off',
    'that won’t leave you, like she did',
    'for first timers',
    'that self destructs after one use',
    'that makes you laugh, but also learn',
    'that beeps when it\'s done',
    'for when there\'s a fire',
    'to get rid of that mayonaise smell',
    'but without that mayonaise smell',
    'for poor people',
    'to organise your steelbook blu-rays',
    'but sings happy birthday',
    'with a headphone socket',
    'for road warriors',
    'for pets',
    'on acid',
    'on steroids',
    'using this one weird trick',
    'with an introduction by Thom Yorke from Radiohead',
    'bundled with a concept album by Coldplay',
    'but better',
    'retrofitted into a NES controller',
    'for developing markets',
    'but for for kids',
    'that could pull down from the top when you click the button'
  ],
}

module.exports = words;