let words = {
	types : [
		`indie platformer`,
		`MMORPG`,
		`farming simulator`,
		`on rails shooter`,
		`live-action video adventure`,
		`arcade platformer`,
		`mobile game`,
		`brain training game`,
		`8-bit platformer`,
		`rhythm game`,
		`survival horror`,
		`dating sim`,
		`multi-player party game`,
		`GTA clone`,
		`text adventure`,
		`escape room simulator`,
		`flight simulator`,
		`kart racer`,
		`tamagotchi knock-off`,
		`interactive film`,
		`Flappy Bird rip-off`,
		`sports sim`,
		`top-down footie game`,
		`strategic business game`,
		`turn based co-op`,
		`micromanager`,
		`surrealism experiment`,
		`snooker management game`,
    `fast paced light-gun epic`,
    `competitive excergame`,
    `digital pinball table`,
		`snooker management game`,
		`slice-of-life adventure game`,
		`turret defense`,
		`educational game`,
    `beat-em-up`,
    `shoot-em-up`,
		`educational game`,
		`suicide simulator`,
		`frogger-style game`,
		`escort mission game`,
    `Apple watch app`,
    `survival sandbox`
	],
	nouns : [
		`Captain Grammar`,
		`eggs`,
		`some eggs`,
		`an egg`,
		`a talking dog`,
		`The Waltons`,
		`a monopoly piece`,
		`a cardboard box`,
		`a 12 man jury`,
		`a spittoon`,
		`the entire population of Luxembourg`,
		`your mum`,
		`Cool Ranch Original Flavour Doritosᵀᴹ`,
		`Tumble dryer repair man`,
		`Guybrush Threepwood`,
		`a tiny farting caterpillar`,
		`tiny farting caterpillar`,
		`the entire cast of Seinfeld`,
		`a nana who has escaped from the retirement home`,
		`an Ocado delivery driver`,
		`a dirty great big jug of farts`,
		`a cop who just handed in their badge`,
		`a grammar nazi`,
		`Tony Hawk`,
		`a human ass`,
		`Wario`,
		`a delicious steak dinner`,
		`a precariously balanced bucket of water`,
		`a big muscly army man`,
		`a watermelon hurtling towards the floor`,
		`the Prime Minister`,
		`Eggles: The egg with legs`,
		`1950's moviestars`,
		`some sort of bird`,
		`the Marlborough Man`,
		`a Great Big Fat Pig`,
		`a pregnant snake`,
		`Terry Wogan`,
		`one of the Pacman ghosts`,
		`a normal homemaker`,
		`one of the guys from Scrubs`,
		`a spaceship`,
		`Ziggy from Quantum Leap`,
		`various historical figures`,
		`Mr Kipling`,
		`Lenny Henry`,
		`any porn star`,
		`Clippy`,
		`snooker players`,
		`Sonic's friends`,
		`a plastic bag blowing in the wind`,
		`a football team`,
		`God and Jesus`,
		`snooker players`,
		`Fraiser Crane, from Fraiser`,
		`a Mother Goose`,
		`the Meatball from Ol' Smokey that got lost when somebody sneezed`,
		`Bjork`,
		`King Herod`,
		`Gary Lineker`,
		`an Online Troll`,
		`either Simon OR Garfunkel, (whoever you don't pick is the final boss!)`,
		`a sexy businessman`,
		`a small business owner`,
		`a really angry Irishman`,
		`the Wall St Bull Statue`,
		`a bad painting of Henry VIII`,
		`either Mulder, Scully, or The Noid`,
		`Frankenstein`,
		`Dracula`,
		`Miss Universe`,
		`a really big clumsy oaf`
	],
	variations : [
		`just trying to find your way home`,
		`trying to kill yourself`,
		`that must defeat the nazi king`,
		`on a mission to find where the moon went`,
		`but the game resets every time you die`,
		`that speeds up exponentially every five minutes`,
		`who must solve crimes by using only household implements`,
		`locked in a room with an angry bee`,
		`who must get off a desert island`,
		`in a fantastic adventure with pirates!`,
		`on skis`,
		`vs Predator`,
		`in a fantastic adventure with pirates!`,
		`but the blocks must line up with the other blocks or something…`,
		`and it's a murder mystery set in an abandoned Butlins`,
		`in a hospital museum`,
		` - it might only run if you have a special dongle`,
		`but you have to use your brain, and also test your balance`,
		`that's fun for pets to watch`,
		`set in the past`,
		`and it's a murder mystery set in an abandoned Butlins`,
		`trying to untangle fairy lights`,
		`evolving and fighting tiny horses`,
		`with unique weapon crafting process`,
		`that eats eggs`,
		`fighting an evil version of yourself`,
		`that has a clever twist at the end`,
		`in a reserved Wiltshire village`,
		`to tie in with the upcoming feature film`,
		`set in a techno music soundscape`,
		`reviewing restaurants`,
		`in the bathroom`,
		`restoring and renovating a hotel`,
		`in space`,
		`trying to predict Office applications based on the file extension`,
		`travelling through Canada`,
		`with optional subtitles`,
		`and you have to score goals`,
		` - whoever gets the most points is the winner`,
		`with glasses`,
		`and you have to keeping moving or you'll die`,
		`with glasses`,
		`and the controls are reversed`,
		`and it works with a dance mat`,
		`and the cast of Gorillaz dance along to it`,
		`and there are several prizes you can choose from`,
		`- it's online, so there's lag`,
    `trying to tame a lion`,
		`the Guitar Hero guitar works with it`,
    `that uses lyrics as a weapon`,
    `with a gun`,
		`and you can use micropayments to buy different hats`,
		`and you get to kiss Sonic at the end`,
		`and you have to kill the bad guys using stealth`,
		`but watch out! The villain is none other than Dr Robotnik!`,
		`but don't crap your pants or it's game over!`,
		`and the Playstation Camera will know if you've left the room`,
		`and you must try not to wake up Grandpa`,
    `trying to chose a date for prom`,
    `driving your friends to the mall`,
    `in a hot air balloon`,
    `and all the characters from Dad's Army`,
    `trying to remember things`,
		`trying to hit a pinata`,
		`trying to take out the garbage`,
		`running a race without bending your knees`,
		`but the sound effects get higher pitched randomly`,
		`and the soundtrack is by Aphex Twin`,
		`and the motion captured Daniel Day Lewis is disturbing`,
		`and you have to figure out who is the murderer`,
		`but which character stole Honest Abe from Mt Rushmore?`,
		`and the age rating is 18+ for obvious reasons`,
		`and it's free online for the first month`,
		`but don't crash into anything or it's all over`,
		`just generally being clumsy and trashing the place`,
		`tumbling wildly down the side of a mountain`,
    `on opposite day`,
	]
};

module.exports = words;
