let words = {
	types : [
		`indie platformer`,
		`MMORPG`,
		`farming simulator`,
		`on rails shooter`,
		`live-action video adventure`,
		`arcade platformer`,
		`mobile game`,
		`brain training game`,
		`8-bit platformer`,
		`rhythm game`,
		`survival horror`,
		`dating sim`,
		`multi-player party game`,
		`GTA clone`,
		`text adventure`,
		`escape room simulator`,
		`flight simulator`,
		`kart racer`,
		`tamagotchi knock-off`,
		`interactive film`
	],
	nouns : [
		`eggs`,
		`some eggs`,
		`an egg`,
		`a talking dog`,
		`The Waltons`,
		`a monopoly piece`,
		`a cardboard box`,
		`a 12 man jury`,
		`a spittoon`,
		`the entire population of Luxembourg`,
		`your mum`,
		`Cool Ranch Original Flavour Doritosᵀᴹ`,
		`Tumble dryer repair man`,
		`Guybrush Threepwood`,
		`a tiny farting caterpillar`,
		`tiny farting caterpillar`,
		`the entire cast of Seinfeld`,
		`a nana who has escaped from the retirement home`,
		`an Ocado delivery driver`,
		`a dirty great big jug of farts`,
		`a cop who just handed in their badge`,
		`a grammar nazi`,
		`Tony Hawk`,
		`a human ass`,
		`Wario`,
		`a delicious steak dinner`,
		`a precariously balanced bucket of water`,
		`a big muscly army man`,
		`a watermelon hurtling towards the floor`,
		`the Prime Minister`,
		`Eggles: The egg with legs`,
		`1950's moviestars`,
		`some sort of bird`,
		`the Marlborough Man`
	],
	variations : [
		`just trying to find your way home`,
		`trying to kill yourself`,
		`that must defeat the nazi king`,
		`on a mission to find where the moon went`,
		`but the game resets every time you die`,
		`that speeds up exponentially every five minutes`,
		`who must solve crimes by using only household implements`,
		`locked in a room with an angry bee`,
		`who must get off a desert island`,
		`in a fantastic adventure with pirates!`,
		`on skis`,
		`vs Predator`,
		`in a fantastic adventure with pirates!`,
		`but the blocks must line up with the other blocks or something…`,
		`and it's a murder mystery set in an abandoned Butlins`,
		`in hospital museum`,
		` - it might only run if you have a special dongle`,
		`but you have to use your brain, and also test your balance`,
		`that's fun for pets to watch`,
		`set in the past`,
		`and it's a murder mystery set in an abandoned Butlins`,
		`trying to untangle fairy lights`,
		`evolving and fighting tiny horses`,
		`with unique weapon crafting process`,
		`that eats eggs`,
		`fighting an evil version of yourself`,
		`that has a clever twist at the end`,
		`in a reserved Wiltshire village`,
		`to tie in with the upcoming feature film`,
		`set in a techno music soundscape`
	]
};

module.exports = words;
